//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pruebas.Entidades.OracleDF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIOS
    {
        [Key]
        public decimal USUARIOID { get; set; }
        [MaxLength(10)]
        public string LOGIN { get; set; }
        public short ACTIVO { get; set; }
        [MaxLength(1000)]
        public string NOMBRECOMPLETO { get; set; }
        [MaxLength(50)]
        public string EMAIL { get; set; }
        public System.DateTime ULTIMOACCESO { get; set; }
    }
}
